// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
// layout/sidebar.templ

package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sidebar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"drawer-side\"><label for=\"drawer\" class=\"drawer-overlay\"></label><ul class=\"menu p-4 w-80 h-full bg-base-200 text-base-content\"><div class=\"flex flex-col h-full\"><div class=\"flex items-center gap-4 px-4 py-2\"><div class=\"avatar placeholder\"><div class=\"bg-neutral text-neutral-content rounded-full w-8\"><span class=\"text-xs\">JP</span></div></div><span class=\"font-semibold\">John Doe</span></div><div class=\"divider\"></div><li><a class=\"active\">📋 All Tasks</a></li><li><a>📅 Today</a></li><li><a>📅 Upcoming</a></li><li><a>⭐ Important</a></li><div class=\"divider\">Categories</div><li><a>🏢 Work</a></li><li><a>🏠 Personal</a></li><li><a>🎯 Goals</a></li><div class=\"mt-auto\"><div class=\"divider\"></div><li><a>⚙️ Settings</a></li></div></div></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
